### ISSUE TITLE
No Chinese dropdown button for FAQ

### ISSUE THREAD

**Issue by kanfibl** [vergecurrency/vergecurrency.com#100]
@gfranko somehow there is no dropdown for Chinese FAQ. Only Russian, German and Korean (screenshot attached).

the link is here: https://vergecurrency.com/langs/zh_CN/faq
<img width="785" alt="screen shot 2017-08-29 at 16 47 29" src="https://user-images.githubusercontent.com/26276624/29827269-c94afd6c-8cd9-11e7-9829-4eeb23734a66.png">

**Comment by gfranko** [comment]
Fixed!
