### ISSUE TITLE
ERC 20 and Verge coin.

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/vergecurrency.com#1127]
I understand that this is not a proper place for this question, but the Medium article isn't very clear.

Will the holders of the Original Verge Coin eventually be forced to convert to the new ERC-20 coin standard?

Can there be a detail post with examples(screen shots if possible) on how to convert the Original Verge Coin to the ERC-20. 
Please include best Wallet to use to get involved in the ERC-20 P.O.S option.

I may be leaving other questions out, not intentional. Work nights and running on fumes.

Thanks for reading. Please direct me to the proper locations if this information is already available.

Thanks,

**Comment by Romeo01234** [comment]
I forgot to add, what is the conversion ratio from Original Verge Coin to new ERC-20?

**Comment by justinvforvendetta** [comment]
@Romeo01234 no- one will be forced to do anything, and the ratio is decided by the market, not us
