### ISSUE TITLE
vergecurrency.exchange link broken

### ISSUE THREAD

**Issue by chey** [vergecurrency/vergecurrency.com#1128]
On the get-verge page the link to https://vergecurrency.exchange produces a SSL error.

https://github.com/vergecurrency/vergecurrency.com/blob/6049059610df08dc0db815657ff2a1acdf9f145a/pages/get-verge.js#L27C40-L27C70

**Comment by justinvforvendetta** [comment]
interesting, thanks for opening the issue, ill look into this right now, and leave this open until its figured out!

**Comment by justinvforvendetta** [comment]
that site doesnt exist anymore i guess
