### ISSUE TITLE
OSX Electrums

### ISSUE THREAD

**Issue by kanfibl** [vergecurrency/vergecurrency.com#120]
could you please add buttons to the wallet section, @gfranko ?

ClearNet:
https://github.com/vergecurrency/electrum-xvg/releases/download/2.4/electrum-xvg-2.4-macosx.dmg
TOR:
https://github.com/vergecurrency/electrum-xvg-tor/releases/download/2.4/electrum-xvg-tor-2.4-macosx.dmg

**Comment by justinvforvendetta** [comment]
@kanfibl he already knows and will be adding them tonight.
