### ISSUE TITLE
Links to miners causing site rating and security warnings - Urgent

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/vergecurrency.com#157]
Google Chrome will give a red page warning if you go to the mining resources. Ratings sites such as Symantec has the whole site categorized as suspicious. I'm proposing that the page be removed from the site.  Links to resources could be put on the new mining pool site, however being careful not to offer direct downloads.

The next step is ask for the page to rerated on all affected systems. Bluecoat link is here. There's at least a dozen other systems.
http://sitereview.bluecoat.com/sitereview.jsp#/?search=vergecurrency.com

**Comment by Technophant** [comment]
I updated all of the mining links to go to crypto blog or github. We could start with that and try asking for reviews.

**Comment by Technophant** [comment]
Next steps: Checking Google's transparency report (https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fvergecurrency.com%2Fmining%2F) it shows that:

**Current status, warning, this site is unsafe.**

The site https://vergecurrency.com/mining/ contains harmful content, including pages that:

- 
    Install unwanted or malicious software on visitors’ computers

Following the links it says assess and clean your site (done) then request a review:
https://developers.google.com/webmasters/hacked/docs/request_review

Must "Verified ownership of your site in Search Console" before requesting.

**Comment by justinvforvendetta** [comment]
sent the review in.

**Comment by justinvforvendetta** [comment]
i think crypto blog is the issue. github wouldnt red flag, and the links on crypto blog dont always come directly from the source code repository

**Comment by Technophant** [comment]
It's still marked as unsafe. This shouldn't be closed until this is resolved.

**Comment by justinvforvendetta** [comment]
yeah i filled out the form. i will change the links to the github repositories. i think the "cryptominingblog" or whatever is what is causing this issue.

**Comment by Technophant** [comment]
Yes, one of the ccminer downloads is flagged. Time to rethink?  The mining resources can be part of the new mining project, so now that fix hasn't worked, time to delete?

**Comment by Technophant** [comment]
How about this: remove the mining page for the time being. Resubmit for review for google and every other rating system that says it's suspicious.  The the page can then be simplified with more detailed info on the mining site.

**Comment by Technophant** [comment]
Closed accidentally. Marked urgent because people are getting malware warnings.

**Comment by Yakuza112** [comment]
maybe prevent this next time with using an url shortening service ?

**Comment by brianerdelyi** [comment]
Google has webmaster tools.  An owner for the site should be registered.  This helps to resolve issues when the site is flagged by blacklists.
