### ISSUE TITLE
Electrum verge wallet install

### ISSUE THREAD

**Issue by jpflug64** [vergecurrency/vergecurrency.com#161]
I have an Electrum BTC wallet that works fine.  I bought XVG with the intent of putting it in a verge wallet on Electrum.  I downloaded the verge wallet for Electrum and ran the .exe.  It doesn't seem to integrate with Electrum in any way I can figure.  When I open Electrum, I have to browse to the Electrum XVG folder and open the default wallet (I didn't get to name it?), but it doesn't seem to give me the ability to receive the XVG and the options are greyed out.  Any ideas?

This is Win64, and it generated the following log:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\pyqtexe27\lib\threading.py", line 801, in __bootstrap_inner
\Downloads\electrum-xvg-win-amd64\electrum-xvg-win-amd64\lib\interface.py", line 287, in run
    s = self.get_socket()
\Downloads\electrum-xvg-win-amd64\electrum-xvg-win-amd64\lib\interface.py", line 164, in get_socket
    s = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23, cert_reqs=ssl.CERT_NONE, ca_certs=None)
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 943, in wrap_socket
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 611, in __init__
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 840, in do_handshake
error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by justinvforvendetta** [comment]
first of all, you opened an electrum issue in the website repo. secondly, i have no idea what you mean. electrum for bitcoin, and electrum for verge, and 2 completely different applications that use entirely different data directories.

**Comment by jpflug64** [comment]
Sorry to be a bother.  If I were an experienced user, I probably wouldn't have to ask for help.

Just trying to put my verge in a safe place.  
    On Sunday, November 5, 2017, 11:20:47 AM EST, sunerok <notifications@github.com> wrote:  
 
 
first of all, you opened an electrum issue in the website repo. secondly, i have no idea what you mean. electrum for bitcoin, and electrum for verge, and 2 completely different applications that use entirely different data directories.

**Comment by justinvforvendetta** [comment]
adding the error helps. so this is what you see after running the electrum-xvg.exe file?

**Comment by jpflug64** [comment]
this is the log.  The wallet opens, and generated a seed, but it will not let me send verge to the wallet--everything is greyed out

    On Sunday, November 5, 2017, 11:35:15 AM EST, sunerok <notifications@github.com> wrote:  
 
 
adding the error helps. so this is what you see after running the electrum-xvg.exe file?

**Comment by justinvforvendetta** [comment]
did you create a normal wallet or multi sig?

**Comment by jpflug64** [comment]
Normal 2fa

**Comment by jpflug64** [comment]
OK--latest status.  I FINALLY got it to work!!  Thank you!!

**Comment by jpflug64** [comment]
Sigh.  I got the XVG moved, theorectically...says it's it the wallet but it is unverified.  What do I have to do to get it verified?  This is a PITA.  Win 64 Electrum XVG wallet SHOULD work, right?  It's REALLY hard to find any information that is helpful to me out on the net.  TOR wallet?  
Two other things--my regular Electrum wallet has 2fa.  XVG wallet does not, and I can't figure out how to make that happen.  Can I set up more than one wallet in Electrum XVG?
Sorry to be a pain, but I really appreciate any help.J
    On Sunday, November 5, 2017, 1:52:07 PM EST, sunerok <notifications@github.com> wrote:  
 
 
did you create a normal wallet or multi sig?

**Comment by justinvforvendetta** [comment]
@jpflug64 its an SPV wallet, so its confirmed once you see it. the unverified thing is just a cosmetic bug. hopefully ill squash it in the next release. and what do you mean by one having 2fa and the other does not? you mean a password/encryption?
