### ISSUE TITLE
faq on different langs

### ISSUE THREAD

**Issue by Yakuza112** [vergecurrency/vergecurrency.com#192]
working fine : https://vergecurrency.com/langs/en/faq/

has empty entries : https://vergecurrency.com/langs/de/faq/ (and other langs too)

https://i.imgur.com/QGzSq4n.png
greyed out example in german are not specified in faq.html .. and if i add them there, they are not specified in english file ... so i have empty entries in eng lang file

already contacted VergeDEV @ Discord about this issue.

**Comment by kanfibl** [comment]
the issue is due to new version of FAQ with new questions. That content is not yet translated/added for other languages

**Comment by Yakuza112** [comment]
i know. so the english version is the "standard" version ?
need to know, to fix other langs

**Comment by SanderNL** [comment]
I can help on the Dutch language if needed.

**Comment by MyBoon** [comment]
Happy to help with French if needed!

**Comment by Tgabox** [comment]
I'll like to get involved. I'll gladly help with the Spanish translation.

**Comment by Technophant** [comment]
I speak Klingon.

**Comment by Chillyo** [comment]
I can translate into Arabic and Farsi.

**Comment by Fillazer** [comment]
I'll help.

I'll post a new branch for French lauguage soon. 👍

**Comment by DelloKrk** [comment]
I could translate from ENG into German and Polish :) ( both nativ lang. )

**Comment by Yakuza112** [comment]
<- German 

 @justinvforvendetta can you provide us one "standard" file ? is the english one the main version, and so we translate from there and ignore the custom phrases which are set on the other languages, which arent available in the english one ?

**Comment by IgorKonovalov** [comment]
Will be glad to help with Russian translation (native)

**Comment by IgorKonovalov** [comment]
completed russian translation of FAQ, please check and merge https://github.com/vergecurrency/vergecurrency.com/pull/241

**Comment by Yakuza112** [comment]
faq issue resolved with pr https://github.com/vergecurrency/vergecurrency.com/pull/220
