### ISSUE TITLE
Links broken from blog page

### ISSUE THREAD

**Issue by deliriumv** [vergecurrency/vergecurrency.com#197]
When viewing the blog https://vergecurrency.com/blog/ all of the links at the top of the page "About" "Get Verge" "Vendors" "Wallets" "Road Map" "FAQ" "P2P Solutions"...etc are broken (404)

**Comment by justinvforvendetta** [comment]
thanks for getting this to our attention @deliriumv

**Comment by Yakuza112** [comment]
working on it, with multi language and better excerpts
just maybe issues with mulitilanguage and Permalinks .. so i need to do some research

https://github.com/Yakuza112/vergecurrency/tree/beta

**Comment by ErvinSabic** [comment]
Has this been fixed yet?

**Comment by Yakuza112** [comment]
nope doesnt seems so .. and i was busy and being ill :/ so i didnt make any progress there

**Comment by datatrustgroup** [comment]
Let me see if I can fix this.

**Comment by matejstrasek** [comment]
Everyone reading latest Wraith Protocol press release are now directed to the blog and therefore have broken menu which gives bad feeling to newcomers. This fix should be prioritised.

**Comment by Yakuza112** [comment]
workaround is there .. dont know if its okay. pull request is out. Definitfly need to find better solution soon
