### ISSUE TITLE
4700+ Confirmation but no coins

### ISSUE THREAD

**Issue by Tubebuzzer** [vergecurrency/vergecurrency.com#217]
I transferred verge coins to my Verge Tor Wallet for Android. There are now 4700 + confirmations but the coins do not credit in my wallet. I have removed and restored the wallet, but no coins. Wallet displays regularly that there is no connection. 

Apps VPN mode is selected for VERGE in Orbot. Any help would be great, thanks.

https://verge-blockchain.info/tx/623406e894d093ac5052b76de9f1da5ab17613fcec3a7f8999cf7870c9e99b28

**Comment by justinvforvendetta** [comment]
and you followed the instructions for if the app says No Connection ?

**Comment by Tubebuzzer** [comment]
On google play I see under 'Whats New' the author states "fix small bug, added more servers for redundancy. if you get "no connection", please follow the instructions below before thinking it doesn't work." 

However I can't find the instructions referenced. I am relatively new, if you could post them here it may help others.

**Comment by justinvforvendetta** [comment]
orbot, top left menu, app VPN mode enable, select everything except verge
