### ISSUE TITLE
coins dissappear in Verge tor Android wallet

### ISSUE THREAD

**Issue by Tubebuzzer** [vergecurrency/vergecurrency.com#219]
The coins appeared in my wallet, however when I went to send coins out of the wallet, the coins dissappear.  After shutdown and restart of the phone, the wallet will show no connection, but the coins will be there. The moment a send to address is input, the coins disappear and the message that not enough funds are available is displayed.

Apps VPN mode is enabled. 

I have set Orbot Apps to include every app except Verge, (this caused other applications to fail), and I have set to exclude all applications except Verge, (this allows my other apps to work properly). Neither configuration seems to help with the issue. The device was restarted after each change in configuration. 

The error I get is 
"Could not send coins: Error
broadcasting transaction:
(hash number entered here)

Could use your help - 👍 
Thank you. 

Updating this thread, my send function worked, I don't know how but I did receive the coins at the other end.  I'll leave this up incase you have info on trouble shooting my issues. Thanks

**Comment by justinvforvendetta** [comment]
maybe you didn't account for fee the first time and were trying to send the entire balance?

**Comment by Tubebuzzer** [comment]
the fee is set to .1, and I didn't change anything when the funds sent. Not sure what is happening here, wish I could describe it better.

**Comment by Yakuza112** [comment]
wrong repository ? pls move

**Comment by Yakuza112** [comment]
@Tubebuzzer maybe you could record it as video

**Comment by Tubebuzzer** [comment]
Its working now and my coins haven't disappeared. I'll try to get it to
repeat, and make a video

**Comment by justinvforvendetta** [comment]
they only disappear if you arent connected. closing
