### ISSUE TITLE
tip to support the Verge Team is incorrect, isnt it?

### ISSUE THREAD

**Issue by 3x0dv5** [vergecurrency/vergecurrency.com#227]
https://vergecurrency.com/langs/en/p2p/
6. Support Verge: tip "**@vergecurrnecy**" to support the Verge Team!

**Comment by 3x0dv5** [comment]
take a look please: https://github.com/vergecurrency/vergecurrency.com/pull/228

**Comment by gfranko** [comment]
This looks like it has been fixed
