### ISSUE TITLE
Update wallet links to latest release

### ISSUE THREAD

**Issue by js0n1** [vergecurrency/vergecurrency.com#239]
Website still links to version 3.0 wallets. This is causing confusion to those new to verge and haven't found the GitHub release page.

**Comment by Yakuza112** [comment]
pull request is already out https://github.com/vergecurrency/vergecurrency.com/pull/232

**Comment by mikeKulasinski** [comment]
Please do not forget to fix links for paper wallet, currently link results in 404 on github.io

**Comment by justinvforvendetta** [comment]
we are going to link the core wallets to the releases tab of the core source code repository, so that users always are brought to the most current release and we dont need to keep updating the link

other wallets will stay respective to their current locations

**Comment by mikeKulasinski** [comment]
Are you planing to update paper wallet from 2.1 ver or this is still good to use ? @justinvforvendetta
