### ISSUE TITLE
New Website 

### ISSUE THREAD

**Issue by JMSantos94** [vergecurrency/vergecurrency.com#246]
Assuming this tweet is real: 
https://twitter.com/RicardoCrypto/status/948514256353480705

Is someone actually working on it? 

I was looking into it, and couldn't find any PR or fork that had any resembling changes.
I would like to contribute 👍

**Comment by justinvforvendetta** [comment]
im waiting to find out as well.

**Comment by JMSantos94** [comment]
@justinvforvendetta I don't mind giving it a try 😎 
Tonight, I will look more into it.

**Comment by Fillazer** [comment]
Not mobile? :/

**Comment by Fillazer** [comment]
I'm graphic designer too, we can expect a great and beautifull website and mobile application for Q1 for sure, I can help if needed!

**Comment by JMSantos94** [comment]
@Fillazer if you have time to mock up a mobile version and a desktop version of the site. Feel free to do so. I am mostly a JavaScript developer, so I will be focusing on that part.

**Comment by JeramyNS** [comment]
If you're re-building the site, can you please change it to a modern framework like Laravel/VueJS?
It wouldn't take more than a day or so to rebuild the current site in that framework.
More than happy to devote some time to make this happen

**Comment by JMSantos94** [comment]
@JeramyNS I had in mind using Gatsby (https://github.com/gatsbyjs/gatsby) and Preact. It will make the page load super fast thanks to the server-rendering and the tiny footprint from Preact. 

We could eventually make a pool to decide which stack to use, while we work on the mocks. Assuming people are cool with removing Jekyll.

**Comment by justinvforvendetta** [comment]
as long as its served from this repo, i dont care what fw we use lol

**Comment by JeramyNS** [comment]
Well Preact and VueJS are both front end frameworks that are often used alongside a backend framework like Laravel or Symfony. I lean more towards laravel because of it's amazing community.

With regards to Preact vs VueJS, the WordPress community has been having a massive discussion in the lead up to Gutenberg. I think they settled with Vue because it's easier to read and the learning curve seems to be smaller.
I personally found Vue to be the fastest thing to code with. Something that I expected to take me a month  only a few days in Vue, so I've been biased ever since.

Anyway, if you wanna go down the laravel/vue path, I could smash something out tonight and tomorrow. 
Just need those new mockups I saw on twitter

**Comment by JMSantos94** [comment]
@JeramyNS Do we even need Laravel at this moment (or any other Backend framework)?
I think to begin with Gatsby could be the perfect replacement for Jekyll, since we can keep the old blog posts on markdown as they are now, and slowly migrate to a content-management system later on. 

What do you mean exactly by "served from this repo" @justinvforvendetta? Are we using Github-pages?
If so https://www.gatsbyjs.org/docs/deploy-gatsby/#github-pages Gatsby would work seamlessly. 

A small article on migrating from Jekyll to Gatsby:
https://www.gatsbyjs.org/blog/2017-11-08-migrate-from-jekyll-to-gatsby/

Anyway, I think the focus now should be coming up with some mocks. I am not a graphic designer, but I will come up with some ideas if nobody volunteers. 

I think we are just wasting Justin's time with framework's discussions. I will ask around our various social media if there is any volunteer graphic designer 😆 🎨

**Comment by JeramyNS** [comment]
True, yeah hosting on github wouldn't be possible with a proper backend framework.

I don't really know best prac and design concepts for Gatsby, so I'll bow out.
I'll keep watch and help out with bugs and UX though. 

I was always more interested in the wallet side of things anyway.

**Comment by JMSantos94** [comment]
Not trying to discourage you from working, and I am not entitled to decide which frameworks we use. As far as I concern this is an open source project, and if you feel like forking the repo and doing the site, I totally encourage you 😎

**Comment by ekryski** [comment]
Gatsby is a pretty good choice imho or [Hexo](https://github.com/hexojs/hexo). I've used a lot of static site-gens including Jekyll but it's getting a bit dated.

@JMSantos94 I'm in favour of Gatsby, React is my jam and will make it easier for us to get contributions and do some really sexy stuff. Happy to help coordinate with you if you wanted to start to kick up a new Gatsby branch.

First order of business might be to see if we can just straight up convert the existing site over and then look at discussing a new layout, design, messaging, etc.

**Comment by JMSantos94** [comment]
@ekryski I haven't try Hexo personally but it looks good. I am down for any React-like framework. I just forked the project and will be working on it this weekend. It would be nice if we could set up a new room on the discord server to coordinate changes unless you have a better idea.

**Comment by paulblochdesign** [comment]
@JMSantos94 @Fillazer @justinvforvendetta  Hi guys, I'm a designer as well and would like to get involved. I previously already started working on a new site design and have been trying to get some feedback or interest from the group. Check it out here: www.futurenomad.com/vergesite.png

I also previously posted some Verge vector graphics for free download which I posted on Behance: https://www.behance.net/gallery/60224395/Verge-Vector-Pack-v1

I design primarily using adobe suite, sketch, and axure (for work, when I have to).

It looks like there may be a number of designers wanting to get involved (that I can see from the discord channel). I'd also be up to organize a sort of design team of volunteers that coordinates with marketing and engineering.

If you want some examples of design work or other credentials let me know, I'll post my linkedin. 

Cheers

**Comment by kade119** [comment]
I'm a UI/UX designer as well, if you need any assistance let me know. @paulblockhdesign that looks clean , love the flat colors especially the dark charcoal with the blue used sparingly.

**Comment by JMSantos94** [comment]
@paulblochdesign your design looks pretty good! 
Let's see what the others say about it.

If you could collaborate with other designers that would be great.

**Comment by ekryski** [comment]
@paulblochdesign can you PR the vector graphics into https://github.com/vergecurrency/verge-graphics if you have not already please? 😄 

Design looks great! A couple minor tweaks I think but let's roll with it. Exactly what I had in mind for polishing things up. People (investors and developers) still aren't aware of just how impactful the new Verge changes are going to be. I think Monero has done a good job of dumbing down what they are doing and making it a bit more approachable. I'd like to do the same, but in a more grown-up tone instead of cartoon-y. You nailed it! 🔨 

Ping me on Discord so that we can coordinate a bit faster on some things. I've been chatting with @JMSantos94 and we're gonna get started. 🎉

**Comment by paulblochdesign** [comment]
@JMSantos94 Sure, what do we need to get the green light? The design is still rough and could use some more work. I think it would be awesome to have the mountain landscape moving and rendered with js or html5. That or we could make it a video looping in the background. 

I think that using a small but talented team of designers and front end coders we could have something really awesome for the next iteration of the site.

Anyway, let me know and we can get something started.

@ekryski thanks and sure! :)

**Comment by justinvforvendetta** [comment]
apparently the person who posted that pic has alot of it done, so im going to see if they can get it up here as soon as they can

**Comment by paulblochdesign** [comment]
@justinvforvendetta get it up as in push to make it live or just here to take a look? How are design decisions made with the Verge community?

**Comment by justinvforvendetta** [comment]
get it up here in at least a branch, if not live. i would prefer it not go live until it has the content from this site on it already, and then mod/evolve it from there, forward.

**Comment by gfranko** [comment]
What's the purpose of a new site?

**Comment by paulblochdesign** [comment]
@gfranko I think it's just constant improvement. Improving the language, content, design, and user experience just as you would better improve the codebase.

**Comment by gfranko** [comment]
@paulblochdesign I think things should always be improved, I just don't want things to be done for the sake of doing something. eg: using a different framework for the site because someone is more comfortable using it

**Comment by ekryski** [comment]
@gfranko wanna ping me on Discord? All the work you have done here is very much respected so I'd love to chat. 😄

**Comment by paulblochdesign** [comment]
@gfranko I'd also add I think there's an opportunity to pool the design talent that's wanting to contribute into a team that's able to organize and deliver assets to the marketing and dev teams consistently. Working together on a new site would be a great first project to deliver on.

**Comment by ekryski** [comment]
@paulblochdesign, @gfranko is a developer actually. However, I agree with everything you said above.

It would be good to hear from whoever else is currently involved in marketing for Verge so we aren't stepping on anyone's toes and can all get aligned. Right now I don't really have an idea who is still around and who isn't. I've had lots of talented people reach out to help on marketing that would love to help so if the people who were previously involved are no longer interested it might make sense to engage the new people.

**Comment by Delicieux** [comment]
So are there people working on the website? I started working on a design myself, but I don't know how far along you guys are and if it's worth the effort to continue. [https://www.dropbox.com/s/sz2jtzxd6blmua1/Vergeweb.jpg?dl=0](url) Or maybe there are people here who'd like to collaborate?

**Comment by paulblochdesign** [comment]
@Delicieux Cool! There's a number of designers here that are interested in collaborating. We are awaiting a newer version of the site to be posted so that we can review it. I've also halted working on further design until we know what's happening. In the meantime, I'd love to take a look at some of your work. Do you have a portfolio online or links to previous work? @JMSantos94 @ekryski  I've started an Issues thread where designers can post their info, let's try and get organized from there: https://github.com/vergecurrency/vergecurrency.com/issues/256

**Comment by jlaureano** [comment]
@JMSantos94 @ekryski @paulblochdesign 
Can we connect to integrate that snapshot of the wallet in the source code?

![image](https://user-images.githubusercontent.com/5193008/34654912-25b5cea8-f3d0-11e7-8113-8d07772f0e79.png)

**Comment by paulblochdesign** [comment]
@jlaureano I wouldn't do that just yet. This isn't a final version of the wallet design (made by waveon3).

**Comment by JMSantos94** [comment]
@jlaureano would be cool to use the mocks from https://twitter.com/waveon3 with his permission of course. Do you need help with the code? I think would be nice to contact him as @paulblochdesign says these mocks aren't finished.

**Comment by justinvforvendetta** [comment]
no we arent posting mock ups on our website.

**Comment by justinvforvendetta** [comment]
we already have a new gui in the works also.

**Comment by paulblochdesign** [comment]
@justinvforvendetta I know you're busy, but do you have time to briefly chat this coming week? I'm coordinating with Hassan aka waveon3 but realize I'm still on the outside looking in. Would be great to talk to you about design et al.

**Comment by BlancetNoir** [comment]
Any updates?

**Comment by gummideepak** [comment]
An update would be nice!? @justinvforvendetta 🥇

**Comment by paulblochdesign** [comment]
Hey everyone,
No one asked but here it is: a Verge rebrand proprosal. Included is a link to the PDF slide deck as well as a video explanation. I finished this weeks ago but have been busy with IRL work and/or sick. Pardon the umms and uhs, I'm not a seasoned youtube celeb...thankfully?

Feel free to leave comments or reach out for whatever reason.

Cheers!

[Download the video presentation](http://futurenomad.com/verge/VERGEMOV_720.mov)
[Download the PDF slide deck](http://futurenomad.com/verge/VERGEBRANDPROPOSALv1.pdf)

@justinvforvendetta @JMSantos94 @ekryski

**Comment by JeramyNS** [comment]
@paulblochdesign well done!
I'm not the biggest fan of the new logo, reminds me a bit too much of dropbox and another company but otherwise it's got some good ideas

**Comment by Fillazer** [comment]
![sans-titre---1](https://user-images.githubusercontent.com/1126668/35372152-6b1b961e-0166-11e8-9ba1-e28555b49c99.png)

**Comment by vsirr** [comment]
Any updates?
