### ISSUE TITLE
Verge-CSIRT

### ISSUE THREAD

**Issue by brianerdelyi** [vergecurrency/vergecurrency.com#253]
To help grow confidence in Verge and XVG, I think it would be helpful to establish a Verge computer security incident response team (CSIRT) based on RFC 2350.

In addition to reactice support, there is other support that can be provided such as publishing security related articles and guidance to the verge community.  In fact, we can help provide security leadership to the crypto coin community as a whole.

**Comment by justinvforvendetta** [comment]
you should contact coinpouch lol

**Comment by brianerdelyi** [comment]
Ouch! :)

Seriously though, I've established these teams with many financial institutions.  Not only does it help show a commitment to security, it can help reduce the impact of security incidents, identify vulnerabilities and build confidence in Verge/XVG.

**Comment by justinvforvendetta** [comment]
yeah thats a great idea

**Comment by brianerdelyi** [comment]
There's a few ways to get started...

1. Discuss in a bit more detail privately.  We should discuss the charter and such.
2. A /security page on the site
3. security@ email address to help with community communication
4. Access to submit posts on the blog

**Comment by ekryski** [comment]
I 100% agree. This is really important.

**Comment by brianerdelyi** [comment]
Now you're getting it :). I'm a big fan of bug bounties as well.  I'm looking forward to getting this going.

**Comment by brianerdelyi** [comment]
Who runs the website?

**Comment by ekryski** [comment]
It's open source. Everyone does. It's hosted from Github here.

**Comment by brianerdelyi** [comment]
Ok, so I see it's not a traditional CMS like Wordpress.  I'll have to see how pages are added and modified.

1. Who is responsible for domain name and DNS?
2. Who approves changes to GitHub?

**Comment by ekryski** [comment]
@justinvforvendetta as far as I know.

**Comment by brianerdelyi** [comment]
Thanks.  In the meantime, I'm getting up to speed on GitHub Pages and Markdown.  I'm drafting an initial landing page for /security to outline the purpose of the team.

What "assets" does Verge have that they feel need to be protected?  I'm thinking the following:

- website
- official communication channels
- verge digital currency

Thoughts?

**Comment by MRSMILEUS** [comment]
How does someone join the security team?

**Comment by brianerdelyi** [comment]
Thanks Mr. Smile.  I'm creating the initial page with charter.  Give me a few days to submit this to the team to let them review before it can be merged into the site and get an email.  In the meantime, are you able to private message me via GitHub?

I expect the main activities will be receiving reports of potential security issues/incidents.  We need to decide what level of help we'll provide to users... I'd want to avoid how-to support.  Regardless, we'll get an idea what type of questions/concerns there are and can publish how-to articles.  I'd really like help with this.

Reports of vulnerabilities will be rare, but we may want a private channel to share with developers (TBD).   Once we have a solution, we can publish advisories.

**Comment by MRSMILEUS** [comment]
Brian i can't seem to see the option to DM you.

**Comment by brianerdelyi** [comment]
You can send me an email, Brian.Erdelyi@gmail.com

**Comment by MRSMILEUS** [comment]
Emailed you. Anyone else interested?

**Comment by brianerdelyi** [comment]
Created charter and submitted pull request #257 .  Pending feedback.

**Comment by datatrustgroup** [comment]
I'm willing to contribute. I work for a global company as a Sr. Systems Engineer (Linux/Redhat/Centos). I've got some programming skills Perl/PHP/Bash. My expertise is in Ddos/Cybersecurity.

**Comment by brianerdelyi** [comment]
Excellent!  Can we connect by linkedIn?

**Comment by datatrustgroup** [comment]
https://www.linkedin.com/in/philipheady/

**Comment by justinvforvendetta** [comment]
@datatrustgroup you went to umass amherst? haha i've been there before.. lived in andover for a while and worked in lowell.

**Comment by datatrustgroup** [comment]
Ya, "Zoo-Mass" and they used to call it 1988-1992.

**Comment by DomCrogan** [comment]
Hey, I'm currently a student in Computing and although I haven't got much experience would love to learn more and help out wherever I can. Not sure if you would need someone like be but thought I'd mention it as the experience would definitely be beneficial for me.

**Comment by brianerdelyi** [comment]
Hi Dom!  Thanks for the support.  I'm waiting for the Verge-CSIRT email to be created and the charter to be published.  Feel free to email or connect with me by LinkedIn.

**Comment by MRSMILEUS** [comment]
Is justin looking into that?

**Comment by brianerdelyi** [comment]
@justinvforvendetta is aware of the thread and I assume the pull request and email request.  We will need to wait for feedback.

**Comment by MRSMILEUS** [comment]
Ok perfect. Yeh I think his busy with the new wallet builds for now
