### ISSUE TITLE
Verge Design Talent

### ISSUE THREAD

**Issue by paulblochdesign** [vergecurrency/vergecurrency.com#256]
This page is meant for interested design talent to post their name, contact information, any portfolio related links, and skills. Many designers have expressed an interest in collaborating and contributing so this is an attempt at self organizing into a group that can work with the devs and marketing team. Let's get to know each other's strengths and find out what's possible. 

Here's my information:

Paul Bloch
Github:@paulblochdesign
Email: paulblochdesign@gmail.com
Discord:Crypton#6732
Website: www.futurenomad.com
Skills/Tools: UI/UX Design, Product Design, Print and web design, Art Direction, Illustration, Adobe Suite, Sketch, Axure
Past Verge Design Ideas: 
http://www.futurenomad.com/vergesite.png
https://www.behance.net/gallery/60224395/Verge-Vector-Pack-v1

**Comment by mitchloidolt** [comment]
Mitch Loidolt
short bio: I do illustration and ui at Obsidian where I've been for 6 years, and previously worked in digital advertising and cartoons for 4 years. I'm a jack of all trades for your random task needs.
email: mitchloidolt@gmail.com
website: [illustration and ui portfolio](https://mitchloidolt.myportfolio.com/)
skills: ui, illustration, apparel design
tools: adobe suite

**Comment by kade119** [comment]
Paul - Great design for the website revamp, only suggestion I see is consider using a couple life style images to help connect the currency to people and convey a more business/professional look and feel.

**Comment by paulblochdesign** [comment]
@kade119 Sounds good, although I resist using stock photos because they come across as campy and/or so generic that they inadvertently communicate inauthenticity. Given the right photos though I'm open. Mind putting down your contact info so we can add it to the master list? Cheers!

**Comment by kade119** [comment]
kadecooper@gmail.com

And I'm not necessarily suggesting stock photos unless it doesn't look "stock", would be nice to find a photographer that can shoot for us.

**Comment by AdventureToursFrance** [comment]
Lifestyle images...? look at my flickr albums... https://www.flickr.com/photos/adventuretoursfrance/albums
I am actually perusing here to see how to get my "going on 4th year Paris tour business" accepting your XVG..? But I can do photography for you all or let's cherry pick what you see in my public albums. Let me know.
Regards, Thor
adventuretoursfrance.com
I am giving my own web site a makeover this moth, prepping for the summer season but I can also do a mock up or two of a general draft of ideas for your site, no problem. I created my first web site in 1996. Worked for a media agency in NYC during the dot com boom. Paris since then doing web until I started the adventure..)
Oh, how do I become part of the vendor listings on the Verge page...?

**Comment by mitchloidolt** [comment]
As far as how to accept XVG payments: I believe most vendors are using Coinpayments.net

**Comment by AdventureToursFrance** [comment]
Thank you. I will look into that. Whatever I need to do I will sign up with coin payments. Is there a kit of logo images for vendors... It's 1:30 AM here in Paris so my day is done.. I will check back to see if I can help with some photos or whatever. Cheers

**Comment by AdventureToursFrance** [comment]
No feedback yet on my photos or offer so I will be lurking here in the French countryside...

**Comment by paulblochdesign** [comment]
@AdventureToursFrance Hi Thor, sorry I haven't had time to respond. Here's some Verge badge drafts if that's what you're looking for. futurenomad.com/verge/vergebadges01.pdf 
I think the idea would perhaps be to have some sort of shot of a storefront or by the cash register. We could simply photoshop in a sticker/badge for Verge. However, it's hard to plan or give you much direction right now when we are in the midst of finishing some first drafts. Great photos! Mind if we message you when we have a better sense of things?

**Comment by AdventureToursFrance** [comment]
Hi Paul, sure, no worries. Yes, please message me whenever you wish. I could return to this shop stuck in time and have a model with a smartphone in-hand displaying Verge on the screen buying something: https://flic.kr/p/GZoQeW
I can do new century photos too, something more cosmopolitan, perhaps...)  I like that shopping bag badge for vendors. Anyway, yeah, I am here, call me when you need me. Regards, Thor
