### ISSUE TITLE
security@vergecurrency.com

### ISSUE THREAD

**Issue by brianerdelyi** [vergecurrency/vergecurrency.com#259]
Who does one request the email address security@vergecurrency.com from for Verge-CSIRT (issue #253)?

**Comment by brianerdelyi** [comment]
@justinvforvendetta Who can create the email alias or IMAP account for security@vergecurrency.com?

**Comment by justinvforvendetta** [comment]
I think we have someone with a CISSP coming to lead the security team, we will post the info shortly

**Comment by brianerdelyi** [comment]
Thanks.  So you want help or dont want help?

**Comment by justinvforvendetta** [comment]
the more the merrier I say!

**Comment by justinvforvendetta** [comment]
I'll leave this open as a discussion thread

**Comment by brianerdelyi** [comment]
I've jumped in to offer help but if you've chosen someone else to lead the security team just let me know.  I need only minimal direction and support (i.e. publishing the security landing page and creating the email alias or IMAP account).  Perhaps we can discuss formalizing the Verge organizational structure and who is responsible for what?

**Comment by brianerdelyi** [comment]
@justinvforvendetta any updates on what we're doing with Verge-CSIRT? Is it something you still wish to pursue?  How about outlining the different Verge teams?

**Comment by datatrustgroup** [comment]
@justinvforvendetta Can we talk soon? I'd like to get involved somehow.

**Comment by justinvforvendetta** [comment]
yep just waiting another 2-3 days for everyone else to show up here and then we'll get it going

**Comment by brianerdelyi** [comment]
Good day.  @justinvforvendetta any updates on who is joining the team and what your plans are for the security team?
