### ISSUE TITLE
Verge wallet showing not connected when initially opened for a while

### ISSUE THREAD

**Issue by zane33** [vergecurrency/vergecurrency.com#260]
Just a suggestion - when new users with Verge Wallet open the wallet and it is out of sync, on the main landing form of the app we should put a quick disclaimer to advise users they need to leave the app open and wait for the app to connect to block chain and sync up.

At present it is very confusing to end users who are first time wallet users and do not know that they need to wait for it.

**Comment by zane33** [comment]
Would be happy to address this issue myself if the Dev's will approve me adding a disclaimer on the main overview tab.

**Comment by cryptoglueck** [comment]
How long does the synch take ?

**Comment by justinvforvendetta** [comment]
only takes about 1 day to sync

**Comment by justinvforvendetta** [comment]
our newest wallet has a progress indicator on the splash screen
