### ISSUE TITLE
Verge Risks

### ISSUE THREAD

**Issue by brianerdelyi** [vergecurrency/vergecurrency.com#274]
Good day.  I’ve been considering various risks that are affecting Verge and would like to hear thoughts from others so we can better plan how to address them.

First, what do you think the top 3 risks are facing Verge?

**Comment by justinvforvendetta** [comment]
as a blockchain, nothing. as a community, third parties are always a risk

**Comment by brianerdelyi** [comment]
I too think blockchain is a reliable and relatively secure technology.

I see Verge (and other digital currencies) primarily being used an an investment (and not a store of value) due to its high volatility.

1. High volatility may be a sign that Verge and other digital currencies are a bubble.
2.  There is a general lack of understanding about Verge (and other digital currencies).  It’s difficult for investors to assess the value of digital currencies, which will succeed and which are scams.
3.  The lack of regulations (although decentralization is generally a good thing) means there is a greater likelihood for scams with Verge (or other digital currencies).

I’d love to hear thoughts from others.

**Comment by justinvforvendetta** [comment]
well regulation wouldn't prevent scams. regardless of regulation, scamming in crypto is just as illegal as scamming people for fiat. unfortunately, that happens with all forms of payment. and i dont think high volatility is a sign of a bubble, we have a large supply and have been around for quite some time, so it makes alot of sense to see volatility. however, we've been pretty lucky as verge has been relatively stable after every large/sudden increase its had. (usually settles to 50% of where it took off from)

**Comment by brianerdelyi** [comment]
I’m not suggesting government regulation is the solution for anything.

It sounds like you don’t agree with risk #1, despite this being a common concern of the industry.

Do you agree with any of the three risks I presented?

Regards,
Brian

**Comment by justinvforvendetta** [comment]
yes absolutely #2. reminds me of this: https://www.youtube.com/watch?v=4APcgsRdW6w

**Comment by brianerdelyi** [comment]
1. I do believe Verge and other digital currencies meet the definition of a bubble:

> "A bubble is an economic cycle characterized by rapid escalation of asset prices followed by a contraction. It is created by a surge in asset prices unwarranted by the fundamentals of the asset and driven by exuberant market behavior. When no more investors are willing to buy at the elevated price, a massive selloff occurs, causing the bubble to deflate." -- Investopedia

Verge and other digital currencies: 1) experience rapid growth and contraction of prices, 2) are impossible or difficult to assess their value and 3) demand for Verge and digital currencies are heavily driven by fear of missing out (FOMO).  The risk is they may be a bubble and if it pop's it will cause massive selloff and drop in price.  I don't think the likelihood (high) and impact (high) should be dismissed.

Read more about what a bubble is (with examples) at https://www.investopedia.com/terms/b/bubble.asp#ixzz54HYNX6Ec 

2. Good video, I think that's pretty much what people hear :).  Gleep, glop, gorp.  If they don't understand it how can they have confidence in it?  This further underscores risk #1.   Likelihood (high) and impact (medium to high).

3. There is a lot of fraudulent activity online combined with the one on security being that of the consumer.  Wallets are hacked/cracked.  Exchanges are hacked/cracked and often go out of business with customer assets, theres a lot of scams that are intended to hype some projects and pump their value up only to dump them back onto the market causing it to fall.  None of this helps to establish consumer confidence and further underscores risk #2.  Likelihood (high) and impact (high).

Thought about these risks?  If others agree we can brainstorm some ideas to help reduce those risks.

Disclosure: I do invest in digital currencies.  I do not own any Verge (XVG).

**Comment by brianerdelyi** [comment]
@justinvforvendetta do you agree with any of these risks or are you interested in doing anything to help reduce them?  Let's talk and do something if you are.

**Comment by maestrus** [comment]
@justinvforvendetta  hi justin i 'd like to know something about implementation public and private ledger in the same blockchain.If you want and if you have the time contact me please.Thank you so much .

**Comment by brianerdelyi** [comment]
@maestrus FYI, this is not the thread for that discussion.  I recommend creating a new issue.

**Comment by gfranko** [comment]
This probably should not be an issue on the site repo and should instead be a reddit thread or on a different forum. Closing for now.
