### ISSUE TITLE
Transferring tokens to new wallet

### ISSUE THREAD

**Issue by peskyrabbit** [vergecurrency/vergecurrency.com#277]
I have an Electrum 2.4.1 wallet for my verge tokens. Problem is I can't remember the password to open it.
Is there a way around this issue. I have downloaded the new 4. wallet but it doesn't show the tokens when synced to the blockchain. I have the addresses for the tokens on the blockchain but how do I get the addresses onto the new wallet. 
I need help to get access to my tokens PLEASE

**Comment by gummideepak** [comment]
@peskyrabbit Did you back up your pass phrase, if you did you can recover the wallet using that and transfer the coins into your new wallet using 'Send Coins' options.

**Comment by peskyrabbit** [comment]
@gummideepak 
[Electrum wallet error message.docx](https://github.com/vergecurrency/vergecurrency.com/files/1645145/Electrum.wallet.error.message.docx)
Thanks for the reply. I created a new wallet with the pass phrase and it is now unlocked. I tried to send a small test amount but I keep getting an error. Please see attached. Are you able to tell me what I need to do?

**Comment by gummideepak** [comment]
@peskyrabbit Never seen that before.You should open a issue here : https://github.com/vergecurrency/VERGE/issues .
This place is only for the vergecurrency website that's why the response is very less!
