### ISSUE TITLE
Public and Private ledger in the same blockchain

### ISSUE THREAD

**Issue by maestrus** [vergecurrency/vergecurrency.com#280]
Hi @justinvforvendetta  sorry if i use github and issue function to ask this thing .I'd like to know how can you be able  to put  in the same blockchain public and private ledger without a fork.
How can you  be able to hide transaction in the ledger?ledger keeps public and private transaction linked in the same chain.How it's possible to hide private transaction in the same chain?
I hope one day you will do a video where you explain to the world how wraithprotocol works .this project is amazing .
I don't know if verge will be the new bitcoin and i don't mind it but i believe your project  is very strong and i  will keep on supporting it.
In the last month many times i heard "scam,wraith not working,verge leaks ip,no privacy" and  i was wondering "why justin doesn't answer to these scammer".Community is strong .
Thank you so much for you time.
P.S
According to you it would possible delivery wallet using container?You could create a container where store wallet in a sort of "sandbox" maybe in this way you could control dependecy library and maybe you could solve some issue.It's only idea.

**Comment by justinvforvendetta** [comment]
we don't need to answer to fud, and yes we will have videos explaining private transactions soon

**Comment by maestrus** [comment]
thank you so much justin.
