### ISSUE TITLE
Android tor wallet link isn't functioning

### ISSUE THREAD

**Issue by Influence2** [vergecurrency/vergecurrency.com#290]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>50223128/fa865a90-a71c-11e7-9e48-f1a05a2eda8f</Key>
<RequestId>025EE33EAF3DD6A1</RequestId>
<HostId>
SfgK83MFc/LksCn8ahegtm3aSWVV92YOQ3jSuyqJj5M6uU+zMmv6PmJXQxsHUlFUQNzJXsIoUsA=
</HostId>
</Error>

**Comment by justinvforvendetta** [comment]
I'll fix this right away, thanks for reporting it!

**Comment by Influence2** [comment]
No problem, someone mentioned it in telegram, so I put it here.

**Comment by Influence2** [comment]
This issue can be closed, Justin committed the update and the link works now.
