### ISSUE TITLE
Fix Verge Mac OSX Wallet Link

### ISSUE THREAD

**Issue by Yakuza112** [vergecurrency/vergecurrency.com#291]
may someone fix the broken link "https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-Qt-23-06-2018.dmg" please ?

**Comment by Influence2** [comment]
Looks like this was commited. Can you try again and see if its ok?

**Comment by justinvforvendetta** [comment]
I fixed it earlier
