### ISSUE TITLE
Verge Debian wallet link needs to be fixed

### ISSUE THREAD

**Issue by CoinCrazy66** [vergecurrency/vergecurrency.com#298]
Seems there's nothing here atm.
https://github.com/vergecurrency/VERGE/releases/download/2.1/debian8_v2.1.0.tar

**Comment by justinvforvendetta** [comment]
oh yeah that's b3cause that was for 2.1, I'll get a deb binary up

**Comment by Yakuza112** [comment]
arch_2.1.0.tar
centos7_2.1.0.tar
debian8_v2.1.0.tar
fedora23_2.1.0.tar
verge-qt-osx.dmg
VERGE-Windows.zip
vergetorandroid.apk 

are "offline" as well too

**Comment by gfranko** [comment]
@justinvforvendetta 

Once it is updated, let's make sure to update these download links: https://github.com/vergecurrency/vergecurrency.com/blob/master/_config.yml#L41-L67
