### ISSUE TITLE
Withdraw Not Found

### ISSUE THREAD

**Issue by Christhany** [vergecurrency/vergecurrency.com#299]
I withdrew XVG from yobit on January 30 2018 to be deposited in my Binance wallet 756.39191577 XVG

Still there is nothing showing up on Binance, and I can find no hash information. 
8f74cc70b01d0dd9d559d90e8465b9d7929faef156e8847bee6b1ac3c808edb2 

I double checked the wallets before I made the transaction.  

Does anyone know what this issue might be.  

Thanks

**Comment by justinvforvendetta** [comment]
yobit is a scam, thats why we dont have them on our website. they never update.

**Comment by Christhany** [comment]
so I will never get my coin?

**Comment by justinvforvendetta** [comment]
you need to open a support ticket with them and hope they respond
