### ISSUE TITLE
more mentions

### ISSUE THREAD

**Issue by justinvforvendetta** [vergecurrency/vergecurrency.com#315]
i think we should link the "mentioned in" directly to the articles.

we were also mentioned in bloomberg

 https://www.bloomberg.com/news/articles/2017-12-20/baby-altcoins-leading-crypto-rally-as-bitcoin-goes-mainstream

forbes:
https://www.forbes.com/sites/jessedamiani/2017/12/19/crypto-watch-verge-xvg-price-climbs-800-in-a-week-what-is-xvg-and-why-is-it-growing-so-fast/

**Comment by Sach97** [comment]
Hi guys, I just made a pull request regarding this pull request #337

**Comment by waveon3** [comment]
We will soon work on a presscoverage page and make sure to list all mentions from recognized media sites.
Preview:
![verge-bootstrap1140-press](https://user-images.githubusercontent.com/38278999/39094560-a0bc0c30-4631-11e8-84a4-3224acb1e869.png)

**Comment by jrsikors** [comment]
I think this is resolved now.  let me know if it's not.
