### ISSUE TITLE
"Trojan:Script/Cloxer.A!cl" in zip-file on your website

### ISSUE THREAD

**Issue by mkoflerAT** [vergecurrency/vergecurrency.com#319]
On your new website - https://vergecurrency.com/ the first button links to this file: https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip

Windows-Defender (on a Win10Pro machine, fully upated) claims that the zip-file contains a trojan:
Trojan:Script/Cloxer.A!cl
![2018-03-25 05_57_17-windows-defender-security-center](https://user-images.githubusercontent.com/15810633/37871591-823010aa-2ff1-11e8-903e-a44a89d0a8a9.jpg)

**Comment by jrsikors** [comment]
@StanFaas you can close this issue as well.  Not much can be done about this.  Windows Defender classifies this as a false positive.
