### ISSUE TITLE
send-an-email.js not found?

### ISSUE THREAD

**Issue by undersound** [vergecurrency/vergecurrency.com#325]
The link to send an email (https://vergecurrency.com/send-an-email)  in the footer is giving a 404 (
https://vergecurrency.com/_next/cd1427ae-937c-43c7-8551-b0af0172f67e/page/send-an-email.js)

**Comment by StanFaas** [comment]
Thanks for the heads up. I'll fix this asap. Thanks!

**Comment by StanFaas** [comment]
Broken link was fixed with above commit.
