### ISSUE TITLE
Add filtering on vendor page

### ISSUE THREAD

**Issue by undersound** [vergecurrency/vergecurrency.com#336]
Usability / content enhancement request here....

First of all, great job on the page https://vergecurrency.com/get-started/! Very nice overview for new users on how to acquire xvg (or any other cryptocurrency basically)

When users have managed to acquire xvg by reading the guide they are provided with a link to all the vendors. (the **See all vendors**" button)  After that they will see a page with all the vendors.

There are a lot of vendors on that page and imo it's not very easy to see which company does what. or with other words where I can spend my xvg on.

Therefore I think it could be helpful to the visitor if they can apply some simple tag based filtering on shopping categories. 

For example ( disclaimer: simple mockup, not a design)
![verge_filter_suggestion](https://user-images.githubusercontent.com/71794/38891073-8676faee-4283-11e8-948b-91925b89847d.png)

Perhaps something like
https://vestride.github.io/Shuffle/ or other filtering plugin

**Comment by jrsikors** [comment]
Good to go on this now ! Will continue to enhance it from here now that we got the base set up:

https://github.com/vergecurrency/vergecurrency.com/pull/511
