### ISSUE TITLE
Missing Image: back-300dpi.jpg

### ISSUE THREAD

**Issue by Jonathan-Garber** [vergecurrency/vergecurrency.com#53]
Replication Instructions

> Download the wallet generator as a zip for offline generation. Open index.html and generate the wallet like normal. You will find the the back image resource is back-300dpi.jpg but the only back image file in images is back300dpi-alt-dogecoin.jpg.

Not exactly feature breaking but annoying none the less.

**Comment by Jonathan-Garber** [comment]
Correction...
The generator I was using was downloaded from the link provided at http://vergecurrency.com/paper-wallet/index.html 

That link goes to - https://github.com/vergecurrency/vergecurrency.com/blob/master/paper-wallet/xvg-paperwallet.zip

When running this generator offline by opening the index.html it will try to load image back-300dpi.jpg which doesn't exist in the images folder.

**Comment by Jonathan-Garber** [comment]
Fairly sure the bundled zip is just out of date.

**Comment by justinvforvendetta** [comment]
yeah we need to just .zip the onsite one, after we have it generating verge addresses again. right now its stuck on btc addresses =\

**Comment by Jonathan-Garber** [comment]
Thank you... You just answered my other question as to why this thing refuses to give me a xvg address as opposed to a btc address.
