### ISSUE TITLE
explorer.vergecurrency.com 404

### ISSUE THREAD

**Issue by Jonathan-Garber** [vergecurrency/vergecurrency.com#54]
Paper Wallet has default directions on the back including how to check your wallet at 
http://explorer.vergecurrency.com
This is a 404

**Comment by justinvforvendetta** [comment]
yeah we need to just zip the contents of the actual website paper wallet, since the .zip hasnt been updated. thanks for the info, we should have this fixed in a day or two the most.

**Comment by Jonathan-Garber** [comment]
Just make note that the current files on git and not the pre packaged archive are the ones still displaying the bad URL. Needs updated before creating the new archive for it. As well as fixing the btc vs xvg address issue etc.
