### ISSUE TITLE
Verge qt wallet not synching/connecting

### ISSUE THREAD

**Issue by cyberjedy** [vergecurrency/vergecurrency.com#547]
### Prerequisites
* [x] Have you pulled the latest version?
Yes
* [ ] Are you reporting to the correct repository?
What?
### Description
I have downloaded and installed the latest Verge qt wallet. On 1 day everything worked like a charm and i did a couple of transactions. Now on day 2 I have no active connections to the verge network anymore. I deactived all the firewalls, reinstalled the wallet, nothing works.

How to solve this? I have searched the existing tickets for solutions, nothing has worked. Now i have tried connecting on two other laptops, and they get the same error. Maybe this has to do with my router?

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

**OS version:** [Windows, Mac etc..]
Windows 10
**What browser:** [Chrome, FF, IE etc..]

**Comment by jrsikors** [comment]
couple things..

#1)  Please post verge wallets under the correct repo for better assistance.  This is for the website and not many monitor it.  This would be the correct repo:
https://github.com/vergecurrency/VERGE/issues

#2)  check out tips and tricks and FAQs on our verge zendesk:
https://verge.zendesk.com/hc/en-us/articles/360015942312-Syncing-is-slow-stuck-will-take-forever
