### ISSUE TITLE
Wrong URL for linux download

### ISSUE THREAD

**Issue by marpme** [vergecurrency/vergecurrency.com#638]
![image](https://user-images.githubusercontent.com/7430964/53172296-4866f280-35e5-11e9-8db0-844132b17f0e.png)

**Comment by marpme** [comment]
Should actually point to this baby: https://github.com/vergecurrency/VERGE/blob/master/doc/build-unix.md

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/vergecurrency.com/commit/719f56ff67a3a430d0042462a57b6b8dac41ad26
