### ISSUE TITLE
BTC Addresses

### ISSUE THREAD

**Issue by Jonathan-Garber** [vergecurrency/vergecurrency.com#64]
Unless I missed something, it looks like the PaperWallet still hasn't been updated to resolve the address generation issue.

When can we expect the PaperWallet to be updated here on GH?

**Comment by JayMaree** [comment]
Hi Jonathan,

Where can we find that particular issue?

**Comment by justinvforvendetta** [comment]
@Jonathan-Garber @JayMaree paper wallet works perfectly. i just created one and imported it into the android tor wallet via qr code scan and it worked perfectly.

**Comment by justinvforvendetta** [comment]
both the .zip and online version are perfect. i think this was udpated within 24 hours of the OP.

**Comment by Jonathan-Garber** [comment]
Just for quick clarification, this issue was not resolved within 24 hours of the OP, it was roughly 4 days later. 

I was monitoring the commits and this one [here](https://github.com/vergecurrency/vergecurrency.com/commit/648230e2c26815cc357293fc043f8e93a275ae32#diff-f72baf163b5eeb9c13921df74eb7e4b8) from Grinfax is where it was resolved.

However, the issue was originally reported on cointalk forums and in reddit, I think about 2 weeks prior to this post.

Just clarifying things. So far everything else from the XVG team has been fairly stable.

**Comment by justinvforvendetta** [comment]
yeah grinfax made the original changes that messed it up, he fixed them. the .zip was always stable though. glad its resolved.

**Comment by Jonathan-Garber** [comment]
The zip archive wasn't stable, it is where I first discovered the error, then I checked the web hosted wallet and found the same error there. Then I downloaded the raw copy and found the same error there as well.

You should know that because you uploaded the fixed archive yourself 8 days ago? or am I missing something here LOL?

**Comment by justinvforvendetta** [comment]
the archive is just the updated appearance. the .zip has always worked. it has a drop down menu and you needed to select verge from it. so yeah, i guess you missed that ;]

**Comment by justinvforvendetta** [comment]
[paper-wallet-v2.zip](https://github.com/vergecurrency/vergecurrency.com/files/1206138/paper-wallet-v2.zip)
thatr the original. you can test it yourself if you like. select verge from the dropdown, good to go.

**Comment by justinvforvendetta** [comment]
id suggest the new one though, since it looks a hell of alot nicer.

**Comment by justinvforvendetta** [comment]
it sounds to me like you didnt select verge in the drop down menu in the original archive though, and thus made a btc address instead of verge.

**Comment by Jonathan-Garber** [comment]
Yea, I don't think I ever adjusted any of the defaults on it. I just ran through entropy generation and discovered I was getting a btc address. So the defaults were just incorrect then.

Could be worse lol. Now if we can just get XVG to increase in value.
