### ISSUE TITLE
NEW WINDOWS WALLET DOES NOT CONNECT TO PEERS

### ISSUE THREAD

**Issue by kevintenda** [vergecurrency/vergecurrency.com#700]
### Prerequisites
* [ ] Have you pulled the latest version? YES
* [ ] Are you reporting to the correct repository? Think so

### Description
The new wallet still doesn't connect to the peers, whereas the old wallet, after downloaded the newly updated blockchain, now sync faster, but after synced the (old) wallet doesn't open as expected and it says 'rescanning...' 

I can't use both wallets

The OS is Windows 64 bit.

**Comment by kevintenda** [comment]
Why have you closed it when you haven't answered it and my wallets still don't work?

**Comment by jrsikors** [comment]
this was posted in the incorrect repo issues page.  vergecurrency.com is for website issues, not wallet issues
