### ISSUE TITLE
Transition Help

### ISSUE THREAD

**Issue by rmphilli** [vergecurrency/vergecurrency.com#727]
Need a good samaritan to walk me through this. I've gone out to the Verge site directly to pull the most recent wallet for Windows. I have an old version of the wallet, on a different computer all together, and would like to transition over to an ios iphone wallet. Could someone reach out with steps about how to install the most updated wallet, then, how to get them on the ios wallet for iphone?

Please and thank you.

Prerequisites
* [ ] Have you pulled the latest version?
* [ ] Are you reporting to the correct repository?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

**OS version:** [Windows, Mac etc..]

**What browser:** [Chrome, FF, IE etc..]

**Comment by jrsikors** [comment]
can you please post this issue over at the other repo:
https://github.com/vergecurrency/VERGE/issues

Have you tried just sending your coins from your old wallet to your iPhone wallet?  It's probably going to be a LOT easier than trying to re-sync wallets, export/import private keys.

**Comment by rmphilli** [comment]
Jeff -

I'll repost over there. Thanks for the advice. I have not --- I read out on the Verge site, and it said explicitly, not to send or receive from out of date wallets. Did I miss something? I would love to send from the old wallet that I have ...

**Comment by justinvforvendetta** [comment]
@rmphilli as long as you backup your wallet.dat, its fine to just replace the old wallet .exe with the new one =]

**Comment by rmphilli** [comment]
I've been trying to fire up my old wallet (back from 2018) for about 2 1/2 days --- it still has 1.2m blocks left to load. I've been out of the crypto game for over a year, so, I'm rebuilding my vocabulary as well as my understanding of how this all works. If anyone would be willing to chat or speak over the phone to walk me through this, please reach out.

**Comment by justinvforvendetta** [comment]
you can email me if you like, justinvforvendetta@gmail.com

**Comment by jrsikors** [comment]
there's also a bunch of good help guides on verge.zendesk.com

like:
https://verge.zendesk.com/hc/en-us/articles/360028180272-Verge-Lumos-v5-Wallet-Installation-Upgrade-Guide-for-Windows

It says v5 but the concepts are the same and still apply for v6

**Comment by rmphilli** [comment]
I followed the V6 wallet download via thew youtube tutorial. How will the new wallet know what my previous balance was on my other wallet?

**Comment by jrsikors** [comment]
You need to copy your old wallet.dat and replace the current wallet.dat.

Make backups of the wallet.dats before you replace, just in case.

**Comment by rmphilli** [comment]
will do, ty

**Comment by rmphilli** [comment]
Just a follow up to say thanks to @justinvforvendetta and @jrsikors - all my xvg funds have been transferred over to my IOS wallet, and my desktop wallet is working great. Thanks again gents.

One follow up question. What is the preferred or recommended way to purchase Verge, to limit transfer fees and get the most xvg for the $?

**Comment by marpme** [comment]
Glad it worked out for you. Sadly we won’t give you any financial advices, please do you own research on how to minimize fees in crypto. Most information is probably findable on our homepage. All the best sir :)
