### ISSUE TITLE
iOS wallet can’t send XVG

### ISSUE THREAD

**Issue by cubsfan1024** [vergecurrency/vergecurrency.com#729]
I have an iOS wallet and can see my coins. I just can’t send them. I try and send and says it fails and says “copayer not found” any help would be appreciated thanks

**Comment by justinvforvendetta** [comment]
@cubsfan1024 are you using the most recent version of the app?

**Comment by cubsfan1024** [comment]
Just saw your email but I did also send in a ticket. Joined the verge currency family.  I believe my phone automatically updates to the latest version. Have iPhone. Not sure it says what version I have but mine does have the Mars and Moon version backgrounds. Again any help would be appreciated.

Thanks 

Jason

**Comment by justinvforvendetta** [comment]
@cubsfan1024  assuming you saved the seed phrase, try deleting the app, and reinstalling, then restoring using the seedphrase. i havent heard of this issue before, but we should start with that =]

**Comment by SwenVanZanten** [comment]
Yo please follow these steps to fix your wallet.

* Check if you have the correct server in the settings
    * Make sure you have the latest update from the AppStore
    * Go to settings > Service URL
    * Tap on the "Use default url" button and wait a bit
    * Check if the funds returned
    * If yes, awesome!
* If that didn't work you can restore your wallet.
    *WARNING: make absolutly sure you have written down the correct paper key and pass phrase when you setup the wallet. To check the paper key again go to settings > paper key.*
    * Go to settings > Remove wallet
    * Tap disconnect
    * You'll see the introduction screen again and choose Restore
    * Fill-in your paper key
    * Then fill-in your pass phrase (the one you used when you setup your wallet!)
    * Proceed the setup
    * Check if the funds returned
    * If yes, awesome!
    * Still not? Wrong paper key and/or pass phrase
    * Try again and carefully fill in your stuff

**Comment by cubsfan1024** [comment]
Thanks.  It worked but very scary. I tapped on the service url button and my coins went from 10 plus million to only a couple hundred coins.  I then restored my wallet and same thing. It showed I only had a couple hundred coins and most of my transactions were gone. I thought somehow I got hacked. But then I did some refreshing...not even sure how....toggled between some pages on app and the coins came back...thankfully. Very odd. But thank you, all resolved.  Jason

**Comment by justinvforvendetta** [comment]
@cubsfan1024 luckily with this wallet, you dont have to worry, because no central server has your coins, and you can always restore your wallet with the seedphrase. if i had to guess, tor was having issues connecting to the server, and it wasnt as serious as it seemed. glad its all working now =]
