### ISSUE TITLE
Website Discord & Telegram links swapped

### ISSUE THREAD

**Issue by amandamarquis1** [vergecurrency/vergecurrency.com#730]
### Prerequisites
* [x] Have you pulled the latest version?
* [x] Are you reporting to the correct repository?

### Description

On the "Find us" tab on the website, the Telegram and Discord links are swapped

### Steps to Reproduce

1. Navigate to vergecurrency.com
2. Click on the "resources" drop down
3. Click on the "Find us" tab

**Expected behavior:** [What you expected to happen]
Links match up with their website's icon
**Actual behavior:** [What actually happened]
The Discord Icon / link appears with the Telegram name
The Telegram Icon / link appears with the Discord name
### Versions

**OS version:** [Windows, Mac etc..]
Windows 10
**What browser:** [Chrome, FF, IE etc..]
Microsoft Edge

**Comment by justinvforvendetta** [comment]
fixed
