### ISSUE TITLE
Add Payget.org to exchange list

### ISSUE THREAD

**Issue by Payget** [vergecurrency/vergecurrency.com#803]
Hello
Our commission-free exchange service gives our customers the opportunity to exchange cryptocurrencies in more than 90,000 exchange pairs.

Our service allows customers to exchange more than 250 cryptocurrencies, we provide the most favorable exchange rate and minimal exchange fees.

We would like to suggest you to place a mention of our service for cryptocurrency holders on your website in the exchange partners section.

Installing our service in your exchange partners section will enable Verge holders to make instant exchange at favorable exchange rates with minimal commissions, without registration.

Advantages of our service: Exchange without commissions, the best exchange rate, 24/7 support, exchange without registration, easy interface.

If there is anything you need to provide for placing our service in the partners section, please contact us and we will provide everything you need.

Official website https://payget.org/
Regards, Payget.org Affiliate Department

**Comment by justinvforvendetta** [comment]
you are an exchange and you have no ssl? @Payget 

let us know if you decide to secure your website.
