### ISSUE TITLE
Language of FAQ switches

### ISSUE THREAD

**Issue by kanfibl** [vergecurrency/vergecurrency.com#92]
The issue is that once you go on the main page, change to Russian and then go to FAQ - the language changes back to English. Would be better if the language chosen on the main page would stays when once the user goes to FAQ.

**Comment by gfranko** [comment]
@kanfibl will fix this in a couple of days max

**Comment by kanfibl** [comment]
any luck?

**Comment by CryptoRekt** [comment]
Did we resolve this? @gfranko

**Comment by Yakuza112** [comment]
its resolved now

**Comment by Yakuza112** [comment]
https://github.com/vergecurrency/vergecurrency.com/commit/8c0c951f752492e2cbbdb1b72682a2e96e931c3b

should be fixed now
